progress:
  in development: sporadic development
ratings:
  stable: 2
  useful: 4
  caliber: 2
  tidy: 3
  tended: 4
  tests: 1
  unique: 7
comment: Probably not feasible to actually work, but still interesting
